version: "3.8"
services:
  backend:
    image: "jeanfrancaise/springboot-react-fullstack:17.2.2023.3.54.39"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
