version: "3.8"
services:
  backend:
    image: "jeanfrancaise/springboot-react-fullstack:16.2.2023.10.9.3"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
