version: "3.8"
services:
  backend:
    image: "jeanfrancaise/springboot-react-fullstack:20.2.2023.5.25.20"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
